### ISSUE TITLE
Crashing Issues

### ISSUE THREAD

**Issue by ghost** [micah686/Visual-Novel-Manager#4]
I tried out 1.1 and program is still crashing for me on both screens. Logs are attached. Also after adding a VN (and subsequently crashing) the program would not start up anymore.
[addvn.txt](https://github.com/micah686/Visual-Novel-Manager/files/404626/addvn.txt)
[login.txt](https://github.com/micah686/Visual-Novel-Manager/files/404625/login.txt)

**Comment by micah686** [comment]
Could you try this version and see if you still have the problem?
[https://dl.dropboxusercontent.com/u/22398345/code/VNM_1.1.0-Hotfix001.zip](url)
That one should fix some of the problems on the VN List tab.
I'll try to look in depth to the crashing later.

Also, could you tell me what the VNID of the game you were trying to add? It would help me try to figure out the cause. It seems like one of the characters from a certain game is causing the crashing, but I need the VNID(s) of the game(s) you were trying to add in order to fix it.

And as for crashing issues, you can delete Database.db and config.json so it starts up properly.

**Comment by ghost** [comment]
Still having problems. Attached are logs for the initial crash and the one time it reached 100% and crashed.  As for VNID I've been trying numbers at random including <a href="https://vndb.org/v3947">Bunny Black</a> and <a href="https://vndb.org/v210">Himawari</a> with the same results.
[debug100%.txt](https://github.com/micah686/Visual-Novel-Manager/files/405680/debug100.txt)
[debug_login1.txt](https://github.com/micah686/Visual-Novel-Manager/files/405679/debug_login1.txt)

**Comment by micah686** [comment]
Closed due to age, and the fact that I will no longer be working on this code.
